name: Build and Publish image to Docker Hub
on: 
  push:
    branches:
      - main

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps :
      - name: checkout
        uses: actions/checkout@v4
      - name: Get branch name
        id: branch_name
        run: echo "::set-output name=current_branch::${GITHUB_REF#refs/heads/}"
      - name: Build image
        run: docker build . -t maharnnops360/amity-cba-report:${{ steps.branch_name.outputs.current_branch }}
      - name: Push image to Docker Hub
        run: |
          docker login -u maharnnops360 -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push maharnnops360/amity-cba-report:${{ steps.branch_name.outputs.current_branch }}

